image: orangecloudfoundry/orange-cf-bosh-cli

stages:
  - deploy

build-deploy-all:
  stage: deploy
  script:
    - echo "Building $CI_PROJECT_NAME"
    - yarn
    - yarn run build-storybook    
    - yarn build
    - cf login -a $CF_URL -u $CF_USER -p $CF_PASS
    - cf target -o "$CF_ORG" -s $CF_SPACE
    - cf push storybook
    - cf push registry
 artifacts:
    paths:
      - web-storybook/storybook-static
      - web/build
  only:
    - dev

production:
  stage: deploy
  script:
    - cf login -a $CF_URL -u $CF_USER -p $CF_PASS
    - cf target -o "$CF_ORG" -s $CF_SPACE
#   - cf push APP NAMES 
  only:
    - master