image: orangecloudfoundry/orange-cf-bosh-cli

stages:
  - deploy

build-deploy-all:
  stage: deploy
  script:
    - echo "Building $CI_PROJECT_NAME"
    - yarn
    - STORYBOOK_MAPBOX_TOKEN=$MAPBOX_TOKEN yarn run build-storybook
    - REACT_APP_MAPBOX_TOKEN=$MAPBOX_TOKEN yarn build
    - cf login -a $CF_URL -u $CF_USER -p $CF_PASS
    - cf target -o "$CF_ORG" -s $CF_SPACE
    - cf push storybook
    - cf push registry
    - cf push presale
  artifacts:
    paths:
      - web-storybook/storybook-static
      - web/build
  only:
    - dev
build-deploy-impactag:
  stage: deploy
  script:
    - echo "Building $CI_PROJECT_NAME"
    - yarn
    - REACT_APP_MAPBOX_TOKEN=$MAPBOX_TOKEN yarn build
    - cf login -a $CF_URL -u $CF_USER -p $CF_PASS
    - cf target -o "$CF_ORG" -s $CF_SPACE
    - cf push registry-impactag
  artifacts:
    paths:
      - web-storybook/storybook-static
      - web/build
  only:
    - dev-impactag
# TBD
#production:
#  stage: deploy
#  script:
#    - cf login -a $CF_URL -u $CF_USER -p $CF_PASS
#    - cf target -o "$CF_ORG" -s $CF_SPACE
#   - cf push APP NAMES
#  only:
#    - master
