[context.production]
  environment = { REACT_APP_API_URI = "https://regen-registry-server.herokuapp.com", GATSBY_API_URI = "https://regen-registry-server.herokuapp.com" }

[context.deploy-preview]
  environment = { PUBLIC_URL = "/", REACT_APP_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9", REACT_APP_API_URI = "https://regen-registry-server-staging.herokuapp.com", GATSBY_API_URI = "https://regen-registry-server-staging.herokuapp.com" }

[[redirects]]
  from = "/registry/*"
  to = "https://regen-registry.netlify.app/:splat"
  status = 200
  force = true
