[build]
  environment = { REACT_APP_API_URI = "https://regen-registry-server-staging.herokuapp.com" }

[context.branch-deploy]
  environment = { REACT_APP_API_URI = "https://regen-registry-server-staging.herokuapp.com" }
