[context.deploy-preview.environment]
  REACT_APP_API_URI = "https://regen-registry-server-staging.herokuapp.com/"

[context.dev.environment]
  REACT_APP_API_URI = "https://regen-registry-server-staging.herokuapp.com/"
