apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: flyway
          image: boxfuse/flyway:5
          args: ["migrate","-url=jdbc:postgresql://{{ .Values.postgresql.fullname }}:5432/{{ .Values.postgresql.postgresDatabase }}","-user={{ .Values.postgresql.postgresUser }}","-password={{ .Values.postgresql.postgresPassword }}","-locations=/flyway-migrations/sql"]
          volumeMounts:
            - name: shared
              mountPath: /flyway-migrations
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: shared
              mountPath: /flyway-migrations
          command: ["cp","-r","sql/","/flyway-migrations"]
      volumes:
        - name: shared
          emptyDir: {}

