backend:
  name: git-gateway
  branch: master
  preview_context: netlify/regen-website/deploy-preview 

media_folder: "web-www/static/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - name: 'pages'
    label: 'Pages'
    media_folder: '../static/media'
    public_folder: '../static/media'
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "web-www/content/homepage.yaml"
        fields:
          - label: "Top Section"
            name: "foldSection"
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Description, name: description, widget: string}
          - label: "Marketplace Section"
            name: "marketplaceSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Body, name: body, widget: text}
              - label: "Call To Actions"
                name: "callToActions"
                widget: list
                collapsed: false
                fields:
                  - {label: "Caption", name: "caption", widget: string}
                  - {label: "Image", name: "image", widget: image}
                  - {label: "Header", name: "header", widget: string}
                  - {label: "Description", name: "description", widget: text}
                  - {label: "Link Text", name: "linkText", widget: string}
      - label: "For Buyers page"
        name: "buyers"
        file: "web-www/content/homepage.yaml"
          - label: "Top Section"
            name: "topSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - label: Body
                name: body
                widget: "object"
                fields:
                  - {label: Start, name: start, widget: string}
                  - {label: Underlined, name: underlined, widget: string}
                  - {label: End, name: end, widget: string}
          - label: "Image Grids Section"
            name: "imageGridSection"
            widget: "object"
            fields:
              - label: "Image Grid Items"
                name: items
                widget: list
                collapsed: false
                fields:
                  - {label: "Header", name: header, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Description", name: description, widget: text}