backend:
  name: git-gateway
  branch: master
  preview_context: netlify/regen-website/deploy-preview 

media_folder: "web-www/static/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - name: 'pages'
    label: 'Pages'
    media_folder: '../../static/media'
    public_folder: '../../static/media'
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "web-www/content/home/index.yaml"
        fields:
          - label: "Top Section"
            name: "foldSection"
            widget: "object"
            fields:
              - {label: Header, name: tagline, widget: string}
              - {label: Description, name: description, widget: string}
          - label: "Marketplace Section"
            name: "marketplaceSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - label: Body
                name: body
                widget: object
                fields:
                  - {label: Green, name: green, widget: string}
                  - {label: Middle, name: middle, widget: string}
                  - {label: Popover, name: popover, widget: string}
                  - {label: End, name: end, widget: string}
              - label: "Call To Actions"
                name: "callToActions"
                widget: list
                collapsed: false
                fields:
                  - {label: "Caption", name: "caption", widget: string}
                  - {label: "Image", name: "image", widget: image}
                  - {label: "Header", name: "header", widget: string}
                  - {label: "Description", name: "description", widget: text}
                  - {label: "Link Text", name: "linkText", widget: string}
          - label: Reverse climate change Section
            name: climateSection
            widget: object
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: "Map Image", name: "image", widget: image}
              - label: Solution
                name: solution
                widget: object
                fields:
                  - {label: Header, name: header, widget: string}
                  - {label: Description, name: description, widget: string}
              - label: Problem
                name: problem
                widget: object
                fields:
                  - {label: Header, name: header, widget: string}
                  - {label: Description, name: description, widget: string}
          - label: CarbonPlus Section
            name: carbonPlusSection
            widget: object
            fields:
              - label: Caption
                name: smallHeader
                widget: object
                fields:
                  - {label: Featured, name: featured, widget: string}
                  - {label: Credit name, name: creditName, widget: string}
              - {label: Header, name: header, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Link text, name: linkText, widget: string}
              - {label: Link URL, name: linkUrl, widget: string}
          - label: Regen Ledger Section
            name: ledgerSection
            widget: object
            fields:
              - {label: Description, name: description, widget: string}
          - label: Why Regen Network Section
            name: valuesSection
            widget: object
            fields:
              - {label: Header, name: header, widget: string}
              - label: "Image Items"
                name: "imageItems"
                widget: list
                collapsed: false
                fields:
                  - {label: "Image", name: "image", widget: image}
                  - {label: "Header", name: "header", widget: string}
                  - {label: "Description", name: "description", widget: text}
      - label: "For Buyers page"
        name: "buyers"
        file: "web-www/content/buyers/index.yaml"
        fields:
          - label: "Top Section"
            name: "topSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - label: Body
                name: body
                widget: "object"
                fields:
                  - {label: Start, name: start, widget: string}
                  - {label: Underlined, name: underlined, widget: string}
                  - {label: End, name: end, widget: string}
          - label: "Approach Section"
            name: "approachSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - label: "Image Items"
                name: imageItems
                widget: list
                collapsed: false
                fields:
                  - {label: "Header", name: header, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Description", name: description, widget: text}
          - label: "Investing Section"
            name: "investingSection"
            widget: "object"
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Note, name: note, widget: string}
              - {label: "Note Link", name: noteLink, widget: string}
              - label: "Items"
                name: items
                widget: list
                collapsed: false
                fields:
                  - {label: "Header", name: header, widget: string}
                  - {label: "Caption", name: caption, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Description", name: description, widget: text}
          - label: "Image Grids Section"
            name: "imageGridSection"
            widget: "object"
            fields:
              - label: "Image Grid Items"
                name: items
                widget: list
                collapsed: false
                fields:
                  - {label: "Header", name: header, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Description", name: description, widget: text}